version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    env_file:
      - docker.env
    networks:
      - postgres

  cloudserver:
    container_name: cloudserver
    image: zenko/cloudserver
    ports:
      - '8000:8000'
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
